package com.zafar.ichatai.ui.screens

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.zafar.ichatai.ui.components.GlassCard
import com.zafar.ichatai.ui.components.GlowBackground
import dev.jeziellago.compose.markdowntext.MarkdownText

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TermsOfServiceScreen(
    onBackClick: () -> Unit = {}
) {
    val colorScheme = MaterialTheme.colorScheme

    val termsContent = """
        # Terms of Service & Privacy Policy
        
        **Effective Date:** July 31, 2026
        **Developer:** Muhammad Sufyan Zafar (iChatAI)
        
        ## 1. Introduction
        Welcome to iChatAI. By using our application, you agree to these terms. Please read them carefully.
        
        ## 2. Data Privacy & Model Training
        iChatAI is a "Client-Side First" application. 
        - **Local Storage:** Your chat history and data are stored locally on your device in a Room database.
        - **Backups:** Optional cloud synchronization is user-initiated via your personal Google Drive.
        - **No Data Harvesting:** We do not store your chats on our servers. Your data is never used by us to train AI models.
        
        ## 3. Credit System & Free Tier
        - **Credits:** Access to AI models is powered by OpenRouter. Each chat interaction consumes 1 credit.
        - **Earning Credits:** You can earn credits through rewarded ads or daily check-ins.
        - **No Cash Value:** Credits are non-refundable and have no monetary value.
        - **Paid Subscriptions:** Pro features and subscriptions are coming soon.
        
        ## 4. Intellectual Property
        - **User Content:** You retain ownership of the inputs you provide and the outputs generated by the AI (subject to the terms of AI model providers).
        - **App Assets:** All software, UI designs, logos, and branding are the exclusive property of Muhammad Sufyan Zafar.
        
        ## 5. Acceptable Use Policy
        You agree not to use iChatAI for:
        - Any illegal activity or promotion of harm.
        - Generating hate speech or harassment.
        - Attempting to "jailbreak" or bypass AI safety filters.
        - Exploiting or manipulating the credit system.
        We reserve the right to terminate access for violations.
        
        ## 6. Limitation of Liability
        - **AI Hallucinations:** AI can provide inaccurate information. Always verify important facts.
        - **Not Professional Advice:** Outputs do not constitute medical, legal, or financial advice.
        - **Disclaimer:** The app is provided "as is" without warranties of any kind.
        
        ## 7. Age Restrictions
        iChatAI is intended for users aged 13 and older. We comply with COPPA and Google Sign-In requirements. Users under 13 are prohibited from using the service.
        
        ## 8. Third-Party Services
        We use OpenRouter for AI models and Google AdMob for rewarded ads. Your use of these services is subject to their respective terms.
        
        ## 9. Contact & Web Links
        For full details, visit our official portals:
        - [Terms of Service](https://ichatai-website.vercel.app/terms)
        - [Privacy Policy](https://ichatai-website.vercel.app/privacy)
        
        If you have any questions, contact us via the app's Support section.
    """.trimIndent()

    GlowBackground {
        Scaffold(
            topBar = {
                TopAppBar(
                    title = {
                        Text(
                            "Terms & Privacy",
                            style = MaterialTheme.typography.titleLarge,
                            fontWeight = FontWeight.ExtraBold,
                            color = colorScheme.onBackground
                        )
                    },
                    navigationIcon = {
                        IconButton(onClick = onBackClick) {
                            Icon(
                                imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                                contentDescription = "Back",
                                tint = colorScheme.onBackground
                            )
                        }
                    },
                    colors = TopAppBarDefaults.topAppBarColors(
                        containerColor = Color.Transparent,
                        titleContentColor = colorScheme.onBackground
                    )
                )
            },
            containerColor = Color.Transparent
        ) { paddingValues ->
            LazyColumn(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(paddingValues)
                    .padding(horizontal = 20.dp),
                verticalArrangement = Arrangement.spacedBy(24.dp),
                contentPadding = PaddingValues(top = 8.dp, bottom = 40.dp)
            ) {
                item {
                    GlassCard(
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Column(modifier = Modifier.padding(16.dp)) {
                            MarkdownText(
                                markdown = termsContent,
                                style = MaterialTheme.typography.bodyMedium.copy(
                                    color = colorScheme.onSurface
                                ),
                                isTextSelectable = true
                            )
                        }
                    }
                }
            }
        }
    }
}
